#!/usr/bin/env bash
# SPDX-License-Identifier: MPL-2.0
#
# Inject compile-time branding into a Floorp-Runtime / Gecko tree (Floorp-style).
# Does NOT download official Firefox binaries — you must full-build after this.
#
# Usage:
#   ./scripts/prepare-runtime.sh /path/to/Floorp-Runtime
#
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
RUNTIME="${1:-}"
if [[ -z "$RUNTIME" || ! -d "$RUNTIME" ]]; then
  echo "Usage: $0 /path/to/Floorp-Runtime-or-gecko-tree" >&2
  exit 1
fi
RUNTIME="$(readlink -f "$RUNTIME")"

if [[ ! -f "$RUNTIME/mach" ]]; then
  echo "Not a Gecko/Runtime tree (missing mach): $RUNTIME" >&2
  exit 1
fi

python3 "$ROOT/scripts/generate-branding.py" \
  --config "$ROOT/brand.config.json" \
  --icons "$ROOT/icons" \
  --out "$ROOT/generated/branding"

BC="$ROOT/scripts/brand_config.py"
ID="$(python3 "$BC" compile-id)"
DISPLAY="$(python3 "$BC" compile-display)"
VENDOR="$(python3 "$BC" vendor)"
N_VARIANTS="$(python3 "$BC" variant-ids | wc -l)"

SRC_BRAND="$ROOT/generated/branding/$ID"
DEST_BRAND="$RUNTIME/browser/branding/$ID"
rm -rf "$DEST_BRAND"
mkdir -p "$RUNTIME/browser/branding"
cp -a "$SRC_BRAND" "$DEST_BRAND"
echo "[prepare] Installed branding → $DEST_BRAND"

# MOZ_APP_NAME: executable + Wayland app_id (Floorp sets this to floorp)
# Prefer mozconfig --with-app-name; also patch confvars if present.
if [[ -f "$RUNTIME/browser/confvars.sh" ]]; then
  if grep -q '^MOZ_APP_NAME=' "$RUNTIME/browser/confvars.sh"; then
    sed -i "s/^MOZ_APP_NAME=.*/MOZ_APP_NAME=${ID}/" "$RUNTIME/browser/confvars.sh"
  else
    echo "MOZ_APP_NAME=${ID}" >> "$RUNTIME/browser/confvars.sh"
  fi
  echo "[prepare] Patched browser/confvars.sh MOZ_APP_NAME=${ID}"
fi

# Write mozconfig for a Linux release-style full build (NOT artifact-builds)
MOZCONFIG_OUT="$RUNTIME/mozconfig.${ID}"
cat > "$MOZCONFIG_OUT" <<EOF
# Generated by floorp-2 prepare-runtime.sh — full compile with custom MOZ_APP_NAME
ac_add_options --enable-application=browser
ac_add_options --enable-release
ac_add_options --disable-tests
ac_add_options --disable-debug
ac_add_options --enable-optimize
ac_add_options --with-branding=browser/branding/${ID}
ac_add_options --with-app-name=${ID}
ac_add_options --with-app-basename=${ID}
ac_add_options --enable-update-channel=release
mk_add_options MOZ_OBJDIR=@TOPSRCDIR@/obj-${ID}
EOF

# Optional: disable updater like portable builds
cat >> "$MOZCONFIG_OUT" <<EOF
ac_add_options --disable-updater
EOF

echo "[prepare] Wrote $MOZCONFIG_OUT"
echo ""
echo "Next (full build, hours, like Floorp-Runtime CI):"
echo "  cd $RUNTIME"
echo "  export MOZCONFIG=$MOZCONFIG_OUT"
echo "  ./mach --no-interactive bootstrap --application-choice browser"
echo "  ./mach configure"
echo "  ./mach build"
echo "  ./mach package"
echo "  # then: $ROOT/scripts/make-appimage-from-dist.sh $RUNTIME/obj-${ID}/dist"
echo ""
echo "Compile brand: ${DISPLAY} (${ID}) vendor=${VENDOR}"
echo "Package variants: ${N_VARIANTS} (see brand.config.json variants[])"
